wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.6
    is_jupyter_run: false
batch_size:
  desc: null
  value: 100
buckets:
  desc: null
  value: 50
epochs:
  desc: null
  value: 50
max_len:
  desc: null
  value: 25
total_params:
  desc: null
  value: 150771
